name: Build and Publish Vault Plugin (ARM64)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-publish:
    name: Build & Push Docker (native arm64)
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Build Vault Plugin Binary
        run: make bin

      - name: Create Dockerfile
        run: |
          cat <<EOF > Dockerfile
          FROM hashicorp/vault:1.19.0
          COPY bin/vault-plugin-auth-jwt /external_plugins/vault-plugin-auth-jwt
          EOF

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image to GHCR
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/vault-plugin-auth-jwt
          docker build -t $IMAGE_NAME:latest .
          docker push $IMAGE_NAME:latest
